import peewee
from flask import Flask

app = Flask(__name__)
app.config.from_object('settings')

db = peewee.MySQLDatabase(app.config["DATABASE_NAME"],
                          host=app.config["DATABASE_HOST"],
                          user=app.config["DATABASE_USER"],
                          passwd=app.config["DATABASE_PASSWORD"])

db.set_autocommit(False)


# This hook ensures that a connection is opened to handle any queries
# generated by the request.
@app.before_request
def _db_connect():
    db.connect()

# This hook ensures that the connection is closed when we've finished
# processing the request.
@app.teardown_request
def _db_close(exc):
    if not db.is_closed():
        db.close()
